Repository QuantStack/jupyterlab-gather, pull requests merged in 2024-05, with the labels that each got.

#4 Update repo links
  .copier-answers.yml
  README.md
  package.json
  src/arCube.ts
Labels: maintenance

#5 Delete server extension
  .github/workflows/build.yml
  README.md
  conftest.py
  jupyter-config/server-config/jupyterlab_arpresent.json
  jupyterlab_gather/__init__.py
  jupyterlab_gather/handlers.py
  jupyterlab_gather/tests/__init__.py
  jupyterlab_gather/tests/test_handlers.py
  pyproject.toml
Labels: maintenance

#6 Run linters
  src/components/modals/DeviceSettingModal.tsx
  style/base.css
Labels: maintenance

#10 Remove vscode settings
  .gitignore
  .vscode/settings.json
Labels: maintenance

#9 Fix UI tests
  .github/workflows/build.yml
  README.md
  ui-tests/tests/jupyterlab_gather.spec.ts
Labels: maintenance

#14 Namespaced CSS
  src/components/Avatar.tsx
  src/components/ControlBar.tsx
  src/components/DeviceSettings.tsx
  src/components/ModelListItem.tsx
  src/components/Peer.tsx
  src/components/PeerSidePane.tsx
  src/components/buttons/PluginButton.tsx
  src/components/buttons/RaiseHandButton.tsx
  src/components/buttons/ScreenShareButton.tsx
  src/components/buttons/SettingsButton.tsx
  src/components/modals/AddNewModelModal.tsx
  src/components/modals/DeviceSettingModal.tsx
  src/components/modals/Modal.tsx
  src/layouts/GridView.tsx
  src/layouts/JoinFormView.tsx
  src/layouts/PresenterView.tsx
  src/layouts/PreviewView.tsx
  src/widgets/LeftSidebar.tsx
  src/widgets/RightSidebar.tsx
  src/widgets/RootDisplay.tsx
  style/base.css
Labels: enhancement

#13 Add StateDB to remember users room code
  README.md
  docs/images/1_landing.png
  docs/images/2_login.png
  docs/images/3_usecase.png
  docs/images/4_role.png
  docs/images/5_dashboard.png
  docs/images/6_roomcode.png
  docs/images/7_jupyter.png
  docs/images/8_gather.png
  package.json
  src/components/MainDisplay.tsx
  src/index.ts
  src/layouts/JoinFormView.tsx
  src/widgets/RootDisplay.tsx
  yarn.lock
Labels: enhancement

#16 Switch to FontAwesome icons
  icons/forbidden.svg
  icons/raised_hand.svg
  package.json
  src/components/ControlBar.tsx
  src/components/Icons.tsx
  src/components/Peer.tsx
  src/components/buttons/PluginButton.tsx
  src/components/buttons/RaiseHandButton.tsx
  src/components/buttons/SettingsButton.tsx
  src/layouts/PreviewView.tsx
  src/widgets/LeftSidebar.tsx
  style/base.css
  yarn.lock
Labels: maintenance

#17 Readme update
  README.md
  docs/images/usage/1_preview.png
  docs/images/usage/2_device_options.png
  docs/images/usage/3_conference.png
  docs/images/usage/4_ar_duck.png
  docs/images/usage/5_model_options.png
  docs/images/usage/6_run_away.png
  docs/usage.md
  src/index.ts
Labels: documentation

#18 Use layout color for the cube
  src/arCube.ts
Labels: enhancement
